### ISSUE TITLE
Error fetching https://ruby.taobao.org/:

### ISSUE THREAD

**Issue by tianqiujie** [alibaba/ruby.taobao.org#10]
➜  ~  sudo gem sources -a https://ruby.taobao.org/
Error fetching https://ruby.taobao.org/:
	no such name (https://ruby.taobao.org/specs.4.8.gz)
➜  ~

**Comment by huacnlee** [comment]
浏览器打开 https://ruby.taobao.org/specs.4.8.gz 试试

**Comment by qhwa** [comment]
已经没有复现，关闭 issue

**Comment by yangtiancheng** [comment]
@qhwa 你是怎么解决的？

**Comment by crhan** [comment]
现在问题还在的话可以 reopen 这个问题 @yangtiancheng
