### ISSUE TITLE
bash: /usr/bin/sass: No such file or directory

### ISSUE THREAD

**Issue by 90arther** [alibaba/ruby.taobao.org#13]
os: ubuntu 14.10
```
sudo gem install sass
```
It print:
```
Successfully installed sass-3.4.16
Parsing documentation for sass-3.4.16
Done installing documentation for sass after 5 seconds
1 gem installed
```
Then I type:
```
sass -v
```
But it didn't work.
```
bash: /usr/bin/sass: No such file or directory
```
I check my sources list :
```
gem sources -l
*** CURRENT SOURCES ***

https://ruby.taobao.org/
http://ruby.taobao.org
```

**Comment by qhwa** [comment]
Can you install sass with official rubygems source and see if it works?

**Comment by 90arther** [comment]
Sorry, I'm in China. I can't connect to rubygems.org.

**Comment by qhwa** [comment]
I guess you uninstalled sass before, and your current `sass` binary is not located in `/usr/bin`. 
To see where it is, run: 

~~~sh
gem env | grep 'EXECUTABLE DIRECTORY'
~~~

**Comment by 90arther** [comment]
I set a proxy. and it works. 
```
sudo gem install --http-proxy http://127.0.0.1:1080 sass
```

**Comment by marianocarrazana** [comment]
just create a link to the gem sass
`
sudo ln /usr/local/bin/sass /usr/bin/sass
`
replace "/usr/local/bin" for your gem directory
`
gem env | grep 'EXECUTABLE DIRECTORY'
`

**Comment by DavidMV97** [comment]
> simplemente cree un enlace a la gema sass
> `sudo ln /usr/local/bin/sass /usr/bin/sass`
> reemplace "/ usr / local / bin" para su directorio de gemas
> `gem env | grep 'EXECUTABLE DIRECTORY'`

yo tuve el mismo problema y esta solución me sirvió , Muchas gracias marianocarrazana
