### ISSUE TITLE
镜像 rails-assets

### ISSUE THREAD

**Issue by qhwa** [alibaba/ruby.taobao.org#14]
https://rails-assets.org/
已经是非常常用的 assets 源了，计划支持

**Comment by crhan** [comment]
这个有手段主动同步吗？还是只能做到第一次请求时缓存？

**Comment by qhwa** [comment]
我还没有研究，理论上可以主动同步。

**Comment by crhan** [comment]
我最早看 rails-assets 的时候他的机制好像还是说用户第一次请求的时候才去做打包，如果还是这个机制的话可能目前已有的镜像策略是没办法满足这个需求的
