### ISSUE TITLE
替换source的顺序要改一下

### ISSUE THREAD

**Issue by rickywrx** [alibaba/ruby.taobao.org#15]
$ gem sources --remove https://rubygems.org/
$ gem sources -a https://ruby.taobao.org/

这两行要换下位置
$ gem sources -a https://ruby.taobao.org/
$ gem sources --remove https://rubygems.org/

因为，你清空后，他会自动补一个初始的，所以最扣还是会有两个
要先加一个淘宝的source，再把原来的删掉。

**Comment by qhwa** [comment]
gem 版本是？

**Comment by qhwa** [comment]
anyway, 改成了这样:
~~~sh
#in one line
gem sources --add https://ruby.taobao.org/ --remove https://rubygems.org/
~~~
