### ISSUE TITLE
使用淘宝gem源，安装时遇到问题

### ISSUE THREAD

**Issue by hanweify** [alibaba/ruby.taobao.org#17]
现使用淘宝gem源进行安装需要ruby的gems,运行指令为：sudo -u git -H bundle install --deployment --without development test postgres aws。但是在安装rugged总是报错，望能解答。错误如下：
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby -r ./siteconf20150919-24990-znwrcm.rb extconf.rb
checking for cmake... no
ERROR: CMake is required to build Rugged.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rugged-0.21.2 for inspection.
Results logged to /home/git/gitlab/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/rugged-0.21.2/gem_make.out
An error occurred while installing rugged (0.21.2), and Bundler cannot continue.
Make sure that `gem install rugged -v '0.21.2'` succeeds before bundling.

**Comment by qhwa** [comment]
1. 日志已经告诉你原因

    > checking for cmake... no
    ERROR: CMake is required to build Rugged.

2. 问题和 gem 源设置无关
