### ISSUE TITLE
error : too many connection resets

### ISSUE THREAD

**Issue by MrBoog** [alibaba/ruby.taobao.org#2]
按照网上所说：http://ruby.taobao.org/
已将source替换：

```
 gem sources -l
*** CURRENT SOURCES ***

http://ruby.taobao.org/
```

但仍然是有error提示：

```
ERROR: Could not find a valid gem 'cocoapods' (>= 0), here is why:
Unable to download data from http://ruby.taobao.org/ - too many connection resets (http://rubygems-china.oss.aliyuncs.com/latest_specs.4.8.gz)
```

系统版本： mac os 10.9
因为最近换电脑了，用的TimeMachine copy的。之前的电脑 gem install 没有任何问题。我在新电脑重新建一个新的用户A，在用户A下面也是没有问题。但当前用户却使很奇怪，一直报错，不知道是否有人遇到过？

**Comment by crhan** [comment]
抱歉。。没有遇到过。。虽然觉得国内应该不会经过防火墙，不过也推荐你默认上 https://ruby.taobao.org 试试看

**Comment by budaodeshu** [comment]
淘宝已经停止了http协议的镜像服务，使用https协议的了，你更换成https://ruby.taobao.org/ 就可以了

**Comment by FromPointer** [comment]
赞， @budaodeshu
