### ISSUE TITLE
基于 OSS 的日下载 log 统计，在页面上显示每日的使用量

### ISSUE THREAD

**Issue by huacnlee** [alibaba/ruby.taobao.org#21]
目的： 大家知道有多少人在用这个；

地址：

http://rubygems-china.oss-cn-hangzhou.aliyuncs.com/logs/rubygems-china2015-10-15-01-00-00-0001
http://rubygems-china.oss-cn-hangzhou.aliyuncs.com/logs/rubygems-china2015-10-15-02-00-00-0001

例如:

``` bash
$ http://rubygems-china.oss-cn-hangzhou.aliyuncs.com/logs/rubygems-china2015-10-15-01-00-00-0001 | wc -l
1528
```

**Comment by qhwa** [comment]
是在首页显示一个数字么？

**Comment by huacnlee** [comment]
对，如果能实现，最好能有月、周、日的统计

另外还能列出每周下载排行的 Gem 更好

最简单当然是显示前一天的下载总数
