### ISSUE TITLE
Can this be rbenv mirror? 

### ISSUE THREAD

**Issue by smilingsun** [alibaba/ruby.taobao.org#22]
Thanks so much for this mirror!
But if I want to install ruby using ``rbenv``, how can I use this mirror?

**Comment by qhwa** [comment]
I find one solution on the internet, but not sure if it works or not:

~~~sh
sed -i 's!ftp.ruby-lang.org/pub/ruby!ruby.taobao.org/mirrors/ruby!'  $(rbenv root)/plugins/ruby-build/share/ruby-build/*
~~~

I will check it later when I'm free from current work.

**Comment by qhwa** [comment]
this command works for me:

~~~sh
env RUBY_BUILD_MIRROR_URL=https://ruby.taobao.org/mirrors/ruby/2.0/ruby-2.0.0-p247.tar.gz# rbenv install 2.0.0-p247
~~~
