### ISSUE TITLE
找不到savon这个包

### ISSUE THREAD

**Issue by mdongsheng** [alibaba/ruby.taobao.org#23]
找不到savon这个包

**Comment by qhwa** [comment]
我试了一下，能装成功最新的 2.11.1

~~~sh
$ gem install savon
Fetching: httpi-2.4.1.gem (100%)
Successfully installed httpi-2.4.1
Fetching: wasabi-3.5.0.gem (100%)
Successfully installed wasabi-3.5.0
Fetching: gyoku-1.3.1.gem (100%)
Successfully installed gyoku-1.3.1
Fetching: nori-2.6.0.gem (100%)
Successfully installed nori-2.6.0
Fetching: savon-2.11.1.gem (100%)
Successfully installed savon-2.11.1
Parsing documentation for httpi-2.4.1
Installing ri documentation for httpi-2.4.1
Parsing documentation for wasabi-3.5.0
Installing ri documentation for wasabi-3.5.0
Parsing documentation for gyoku-1.3.1
Installing ri documentation for gyoku-1.3.1
Parsing documentation for nori-2.6.0
Installing ri documentation for nori-2.6.0
Parsing documentation for savon-2.11.1
Installing ri documentation for savon-2.11.1
Done installing documentation for httpi, wasabi, gyoku, nori, savon after 1 seconds
5 gems installed
~~~

**Comment by mdongsheng** [comment]
嗯， 抱歉， 我发现可能是我搞错了。/苦笑

2015-10-18 20:41 GMT+08:00 qhwa <notifications@github.com>:

> 我试了一下，能装成功最新的 2.11.1
>
> $ gem install savon
> Fetching: httpi-2.4.1.gem (100%)
> Successfully installed httpi-2.4.1
> Fetching: wasabi-3.5.0.gem (100%)
> Successfully installed wasabi-3.5.0
> Fetching: gyoku-1.3.1.gem (100%)
> Successfully installed gyoku-1.3.1
> Fetching: nori-2.6.0.gem (100%)
> Successfully installed nori-2.6.0
> Fetching: savon-2.11.1.gem (100%)
> Successfully installed savon-2.11.1
> Parsing documentation for httpi-2.4.1
> Installing ri documentation for httpi-2.4.1
> Parsing documentation for wasabi-3.5.0
> Installing ri documentation for wasabi-3.5.0
> Parsing documentation for gyoku-1.3.1
> Installing ri documentation for gyoku-1.3.1
> Parsing documentation for nori-2.6.0
> Installing ri documentation for nori-2.6.0
> Parsing documentation for savon-2.11.1
> Installing ri documentation for savon-2.11.1
> Done installing documentation for httpi, wasabi, gyoku, nori, savon after 1 seconds
> 5 gems installed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alibaba/ruby.taobao.org/issues/23#issuecomment-149007841>
> .
>



-- 
http://www.madongsheng.net/ <http://www.kanxiaohua.net/>
