### ISSUE TITLE
Unable to download data from http://ruby.taobao.org/ - bad response Not Found 404 (http://ruby.taobao.org/specs.4.8.gz)

### ISSUE THREAD

**Issue by cnyyk** [alibaba/ruby.taobao.org#26]
➜  /  gem sources -l
*** CURRENT SOURCES ***

http://ruby.taobao.org/
➜  /  gem install rails
ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from http://ruby.taobao.org/ - bad response Not Found 404 (http://ruby.taobao.org/specs.4.8.gz)
➜  /

**Comment by huacnlee** [comment]
use `https://ruby.taobao.org`
