### ISSUE TITLE
bundle install 失败

### ISSUE THREAD

**Issue by alvinzhoux** [alibaba/ruby.taobao.org#29]
bundle install 失败，看上去是
http://ruby.taobao.org/quick/Marshal.4.8/sqlite3-1.3.8-x86-mswin32-60.gemspec.rz
打不开，下面是详细信息，请问一下是什么原因，如何解决。

另：Gemfile中有 gem 'sqlite3'

alvin@ubuntu:~/working/blog$ bundle install -V
Fetching from: http://ruby.taobao.org/api/v1/dependencies
Fetching source index from http://ruby.taobao.org/
Resolving dependencies...Fetching from: http://ruby.taobao.org/quick/Marshal.4.8/sqlite3-1.3.8-x86-mswin32-60.gemspec.rz

Net::HTTPNotFound: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.7</center>
</body>
</html>
Bundler::HTTPError: Net::HTTPNotFound: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.7</center>
</body>
</html>

/home/alvin/.rvm/gems/ruby-1.9.3-p429/gems/bundler-1.3.5/lib/bundler/fetcher.rb:229:in `fetch'
/home/alvin/.rvm/gems/ruby-1.9.3-p429/gems/bundler-1.3.5/lib/bundler/fetcher.rb:92:in `fetch_spec'
/home/alvin/.rvm/gems/ruby-1.9.3-p429/gems/bundler-1.3.5/lib/bundler/remote_specification.rb:46:in `_remote_specification'

**Comment by qhwa** [comment]
改用 HTTPS

**Comment by alvinzhoux** [comment]
thx
