### ISSUE TITLE
index_en.html: Aliyun OSS link in footer is incorrect

### ISSUE THREAD

**Issue by bcooney** [alibaba/ruby.taobao.org#31]
On https://ruby.taobao.org/index_en.html the link to Aliyun OSS has an incorrect URL.

Is: `http://oss.aliyuncom/`
Should be: `http://oss.aliyun.com/`

Since this is the English site, you may want to link to the [English description of Aliyun OSS.](http://www.aliyun.com/product/oss/?spm=5176.383338.201.8.erl7S0&lang=en)

**Comment by qhwa** [comment]
Thank you @bcooney

**Comment by bcooney** [comment]
sure, happy to help!
