### ISSUE TITLE
如何保证所有源的安全性和完整性

### ISSUE THREAD

**Issue by niuniulove** [alibaba/ruby.taobao.org#32]
您们所作的工作是善举，从心底里感谢您们。但我的问题是，所有镜像的packages是否有和源文件一样的hash(md5 or sha#)值，以此保证没有被”第三方“恶意修改过。谢谢！

**Comment by qhwa** [comment]
目前确实有这样的风险
1. rubygems.org 有在页面上提供 gem 的 SHA，但是 mirror 没有。用户只能下载 gem 后和官方源做比对
2. 上游存储是 Amazon S3，可以通过 HTTPS 提高安全性
