### ISSUE TITLE
Travis CI 上的 Ruby 程序包

### ISSUE THREAD

**Issue by franklinyu** [alibaba/ruby.taobao.org#35]
RVM 会优先搜索 Travis CI 上编译好的 Ruby MRI 程序。有考虑镜像这些程序么？直接下载程序比本地编译轻松很多。因为只提供 Ubuntu 和 OS X 上的程序且只有最新的几个版本，看起来总体积也不是很大。

**Comment by qhwa** [comment]
这个可以有，我看一下 rvm 的源码
