### ISSUE TITLE
安装pods碰到服务器文件404的问题

### ISSUE THREAD

**Issue by xiaoxiaozai** [alibaba/ruby.taobao.org#37]
WARNING:  Unable to pull data from 'http://ruby.taobao.org/': bad response Not Found 404 (http://ruby.taobao.org/latest_specs.4.8.gz)
WARNING:  Unable to pull data from 'http://ruby.taobao.org/': bad response Not Found 404 (http://ruby.taobao.org/specs.4.8.gz)

**Comment by huacnlee** [comment]
https
