### ISSUE TITLE
Gem 源同步滞后近一周

### ISSUE THREAD

**Issue by fantasticfears** [alibaba/ruby.taobao.org#38]
新年快乐🐵🎉。

`gem source`:

```
*** CURRENT SOURCES ***

https://ruby.taobao.org/
```

`gem install 'email_reply_trimmer' -v 0.0.6`:
`ERROR:  Could not find a valid gem 'email_reply_trimmer' (= 0.0.6) in any repository`

Feb 8 更新的包，近一周了，还没有同步到淘宝源。

https://rubygems.org/gems/email_reply_trimmer/versions/0.0.6

**Comment by huacnlee** [comment]
同步的时候连接官方，老会连不上，同步其实挺困难的

**Comment by fantasticfears** [comment]
了解了...原来是你们也连不上官方...

**Comment by hging** [comment]
Gem::RemoteFetcher::FetchError: bad response Not Found 404 (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/gems/font-awesome-rails-4.5.0.1.gem)
貌似最近是出现问题了么. 一些 gem 地址404

**Comment by agate** [comment]
@huacnlee 有办法解决么? 是不是意味着应该自己代理然后使用官方源?

**Comment by louis-sherren** [comment]
能否在https://ruby.taobao.org/贴出最后一次同步成功的时间？

**Comment by qhwa** [comment]
现在已经改成通过代理同步了，目前看日志，同步比较流畅了。

**Comment by fantasticfears** [comment]
情况有所改善了，谢谢你们的努力。

**Comment by qhwa** [comment]
虽然问题已经解决，不过 @louis-sherren 的建议挺好的，可以显示最后一次同步成功的时间。

**Comment by louis-sherren** [comment]
@qhwa 包括npm.taobao.org之类的都可以加上，在国内就指望淘宝的镜像了。

**Comment by agate** [comment]
:+1:

**Comment by lenage** [comment]
貌似还是没没有完全同步？ 

``

**Comment by HuangShaoyan** [comment]
我们尝试gem install sigh，只能拿到1.3.1版本。3月3日发布的1.4.0和3月9日发布的1.4.1都没有看到。是不是源同步又出现滞后了？

**Comment by wangyang0918** [comment]
好像更新确实滞后了很多了，3.5号的源今天还没更新

**Comment by hging** [comment]
多关注 ruby-china 会发现 这个不怎么维护了.  建议迁移到 https://gems.ruby-china.org/

**Comment by HuangShaoyan** [comment]
谢谢hging。ruby-china上确实能看到最新的gem了，又多了一个选择。

**Comment by crhan** [comment]
上周修复了一下，本问题先关闭了，如有问题再打开
