### ISSUE TITLE
rubygems-china.oss.aliyuncs.com SSL 证书存在问题

### ISSUE THREAD

**Issue by huacnlee** [alibaba/ruby.taobao.org#4]
Could not verify the SSL certificate for
https://rubygems-china.oss.aliyuncs.com/quick/Marshal.4.8/…….

There is a chance you are experiencing a man-in-the-middle attack, but most likely your
system doesn't have the CA certificates needed for verification. For information about
OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your
Gemfile sources and change 'https' to 'http’.

**Comment by qhwa** [comment]
重现不了这个问题，检查了一下网站 SSL 证书，也是正常的
https://www.sslshopper.com/ssl-checker.html#hostname=rubygems-china.oss.aliyuncs.com

你可能真的被中间人攻击了

**Comment by huacnlee** [comment]
最近好多用户反馈了，我家里也这样，电信网络

**Comment by qhwa** [comment]
发现问题了

* 证书签发给的是 `*.oss-internal.aliyuncs.com`
* 实际域名是 `rubygems-china.oss.aliyuncs.com`

fixing

**Comment by huacnlee** [comment]
oss-internal.aliyuncs.com 是阿里云内部网络域名，不能改改成那个

**Comment by qhwa** [comment]
OSS 上做了一些修改，暂时没有发现证书错误了。继续观察中
