### ISSUE TITLE
The requested url does not exist(22): 'https://ruby.taobao.org/mirrors/ruby/2.1/ruby-2.1.8.tar.bz2'，文件不存在！

### ISSUE THREAD

**Issue by Neweblog** [alibaba/ruby.taobao.org#40]
rvm install 2.1.8 或者 rvm install 2.1报上述错误。
https://ruby.taobao.org/mirrors/ruby/2.1/ 下没有ruby-2.1.8.tar.bz2文件，在https://ruby.taobao.org/mirrors/ruby/下有，请检查一下是否没有做文件链接。

**Comment by crhan** [comment]
现在看是有的，所以就关闭了
