### ISSUE TITLE
证书校验失败

### ISSUE THREAD

**Issue by pangkk18** [alibaba/ruby.taobao.org#43]
gem install sass时，证书校验失败。
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/quick/Marshal.4.8/sass-3.4.21.gemspec.rz)

**Comment by liumf** [comment]
我也遇到这种问题 ，求答案

**Comment by Gaohaoyang** [comment]
同遇到！！！镜像坏掉了吗？

```
λ gem update jekyll
Updating installed gems
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)
```

```
λ gem install rails
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/quick/Marshal.4.8/rails-4.2.5.2.gemspec.rz)
```

**Comment by Gaohaoyang** [comment]
我重新安装了一下ruby，又好了，不知道是安装好的还是因为我刚刚的网络问题。

之前ruby版本：2.2.2
当前ruby版本：ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

**Comment by wpinkey** [comment]
遇到同样的问题，几台pc都这样，ruby版本是2.0.0，尚未解决。

**Comment by Gaohaoyang** [comment]
@wpinkey 试试升级 ruby 看看能否解决。

**Comment by wpinkey** [comment]
@Gaohaoyang 升级到2.2.2p95，依然存在同样问题，难道也要升级到2.2.4！

**Comment by heaquan** [comment]
我就是ruby 2.2.4p230 版本，还是同样的问题

**Comment by 4nix** [comment]
网上的证书能安装jekyll, 但安装不了bundler

**Comment by huyajie** [comment]
C:\Users\h_yajie>gem sources -a https://ruby.taobao.org/
Error fetching https://ruby.taobao.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: ce
rtificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/spe
cs.4.8.gz)

**Comment by huyajie** [comment]
重装  也不好使

**Comment by crhan** [comment]
统一去 #54 更新最新情况，这边关闭了
