### ISSUE TITLE
貌似最近更新的Gems没有同步。

### ISSUE THREAD

**Issue by mooosu** [alibaba/ruby.taobao.org#44]
Could not find bcrypt-3.1.11 in any of the sources
Could not find sprockets-rails-3.0.4 in any of the sources

**Comment by santochan** [comment]
+1 for this.
sidekiq-4.1.1 was released on March 4, 2016. But it isn't on this mirror so far.

**Comment by augus-zz** [comment]
+1 for this.
there is sidekiq-4.1.0 only.

**Comment by emn178** [comment]
+1, please fix it

**Comment by santochan** [comment]
This is the new mirror:  https://gems.ruby-china.org/ . It works fine.

**Comment by crhan** [comment]
fixed
