### ISSUE TITLE
这个ERROR 是怎么回事

### ISSUE THREAD

**Issue by taosapp** [alibaba/ruby.taobao.org#45]
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/quick/Marshal.4.8/openssl-0.2.0.gemspec.rz)

**Comment by crhan** [comment]
跟 #54 情况类似，麻烦给一下 `openssl s_client -host rubygems-china.oss-cn-hangzhou.aliyuncs.com -port 443` 的输出

**Comment by crhan** [comment]
统一去 #54 更新最新情况，这边关闭了
