### ISSUE TITLE
设置淘宝的gem源时，提示证书校验失败

### ISSUE THREAD

**Issue by Blue-Jing** [alibaba/ruby.taobao.org#46]
C:\Users\Administrator>gem sources -a https://ruby.taobao.org/
Error fetching https://ruby.taobao.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

我把ruby彻底卸载重装了一遍 已经没问题了 
最笨的方法：
                     1、正常卸载rubyinstaller；
                     2、清理注册表垃圾；
                     3、用win7系统的搜索功能搜索关键字gem，把和ruby相关的文件全删除；
先前重装的时候应该是卸载的不干净，导致多次重装都无效
还可以尝试：创建环境变量SSL_CERT_FILE，设置value指向cacert.pem

**Comment by heaquan** [comment]
同样的问题，望解决

**Comment by purplebamboo** [comment]
同样的问题，不过应该不是 源的问题，是证书验证的问题  是否可以 302跳到http而不是https。

**Comment by Blue-Jing** [comment]
我把ruby彻底卸载重装了一遍 已经没问题了 
先前重装的时候应该是卸载的不干净，导致多次重装都无效

**Comment by WangLei1993** [comment]
同样的问题，望给个解决方法。

**Comment by soyaine** [comment]
需要下载安全证书文件。
参考http://blog.fens.me/jekyll-bootstarp-github/

**Comment by Gaohaoyang** [comment]
@Blue-Jing 请问你是如何清理注册表垃圾的？

**Comment by Blue-Jing** [comment]
@Gaohaoyang 用360带的清理注册表垃圾工具，你也可以网上搜索有很多

**Comment by jfdsies** [comment]
@soyaine 的方法实测有效，谢谢。参考"下载认证文件"那一段，添加后重新打开命令行（windows下）就可以添加了。

**Comment by Morii120** [comment]
同样的问题，重装还是不行

**Comment by crhan** [comment]
跟 #54 情况类似，麻烦给一下 `openssl s_client -host rubygems-china.oss-cn-hangzhou.aliyuncs.com -port 443` 的输出

**Comment by crhan** [comment]
统一去 #54 更新最新情况，这边关闭了
