### ISSUE TITLE
rugged 没有0.24版本

### ISSUE THREAD

**Issue by bubbleatgit** [alibaba/ruby.taobao.org#47]
rugged 没有0.24版本

**Comment by bubbleatgit** [comment]
Fetching gem metadata from https://ruby.taobao.org/........
Fetching version metadata from https://ruby.taobao.org/..
Could not find gitlab_git-9.0.3 in any of the sources

`gitlab_git-9.0.3`这个也少了

**Comment by swpustc** [comment]
升级gitlab时也是少了这个源，可以使用https://gems.ruby-china.org/ 源替代。
http://stackoverflow.com/questions/36125968/could-not-find-rugged-0-24-0-in-any-of-the-sources

**Comment by bubbleatgit** [comment]
已经改用ruby-chinia的源了

2016-03-24 17:27 GMT+08:00 Wanpeng Song notifications@github.com:

**Comment by crhan** [comment]
抱歉同步有点问题，目前已经 fix 了。另外，用 ruby-china 的源也是可以的。
