### ISSUE TITLE
Unable to download data from https://ruby.taobao.org/

### ISSUE THREAD

**Issue by MrBoog** [alibaba/ruby.taobao.org#48]
换电脑了，配置一堆问题。目前执行 gem install cocoapods 报错有人遇到吗？？

`Unable to download` data from https://ruby.taobao.org/

```
Unable to download data from https://ruby.taobao.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/latest_specs.4.8.gz)
```

**Comment by bubbleatgit** [comment]
我这里是一堆东西下载不到，不知道是不是taobao源出问题了？

**Comment by MewX** [comment]
```
C:\Windows\SysWOW64>gem sources --add https://ruby.taobao.org/
Error fetching https://ruby.taobao.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

```

Same problem :(

**Comment by qhwa** [comment]
抱歉，我已经不再维护 ruby.taobao.org。
社区目前推荐新的源：
https://ruby-china.org/topics/29250

**Comment by bubbleatgit** [comment]
`阿里的网络安全要求维护服务器得是公司员工`

阿里云这么抠！

**Comment by crhan** [comment]
跟 #54 情况类似，麻烦给一下 `openssl s_client -host rubygems-china.oss-cn-hangzhou.aliyuncs.com -port 443` 的输出

另外，没有人“应该”为这个项目付出什么，也没有公司“应该”为这个项目付出什么。请不要建立在这两个任一一个前提下来评判当前的情况 @bubbleatgit

**Comment by bubbleatgit** [comment]
@crhan 既然不提供更新维护了,为什么ruby.taobao.org没有任何公告,既然提供了服务为何不负责到底.

**Comment by crhan** [comment]
没人说不提供更新维护，也没人说要继续更新维护，你可以理解当前是在一个纠缠态中。上文中只是 @qhwa 同学说他个人不再维护了，至于后面到底怎么搞，目前已经有了一些进展。

提供了服务没钱赚有啥好负责到底的，你行你上，不行别那啥对吧。

另外，当前这个 SSL 问题你可以看一下这篇 https://gist.github.com/luislavena/f064211759ee0f806c88 说的很针对性。

**Comment by tangrong** [comment]
@bubbleatgit  ruby.taobao.org 会持续维护下去的，只是换了同学维护而已，有问题也会解决的。

**Comment by bsed** [comment]
oh, I leave the pit 
https://ruby-china.org/topics/29250

**Comment by bubbleatgit** [comment]
@tangrong 喜欢这位同学的说法，@crhan 这个人是吃了火药了？

反正我已经给USTC提过issue，他们已经把上游改为rubygems.org了，我现在已经改用ustc或者ruby-china社区的。不再用ruby.taobao.org了

同时感谢@tangrong的回复。

**Comment by maojj** [comment]
不再维护的话， 主页上说明下吧。  https://ruby.taobao.org/

**Comment by muoji-zhang** [comment]
淘宝利用开源软件获得的大量的经济效益，却帮助开发gfw，连带把大量开源软件墙了。现在连国内的源都不原意支持，送淘宝员工一句：别跟着马骗子卖假货了，挣钱要讲良心。

**Comment by bsed** [comment]
@muoji-zhang ^.^
