### ISSUE TITLE
Could not find email_reply_trimmer-0.1.1 in any of the sources

### ISSUE THREAD

**Issue by coin8086** [alibaba/ruby.taobao.org#50]
根据 https://rubygems.org/gems/email_reply_trimmer 的结果：
0.1.1 - March 7, 2016 (25.0 KB)

这个版本在3月7号初就发布了，但是taobao镜像至今（3月21号）没有：（

请尽快加上。

另：你们的镜像多久同步一次呢？

谢谢

**Comment by crhan** [comment]
fix 了，后端同步有点问题，还有问题再打开吧
