### ISSUE TITLE
Error fetching https://ruby.taobao.com:SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

### ISSUE THREAD

**Issue by merlynee** [alibaba/ruby.taobao.org#51]
添加淘宝镜像地址的时候会报这个错，是为什么啊，用括号里的地址也不行，多谢解答一生平安
Error fetching https://ruby.taobao.com:SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

**Comment by merlynee** [comment]
http://blog.csdn.net/leorowe/article/details/41968349

知道了按照这个做的可以，另外这块已经不维护了，换成了https://ruby-china.org/topics/29250。

**Comment by crhan** [comment]
如有可能，还是希望帮忙使用下面的命令提供一下报错的具体信息，更新到 #54 中去

``` bash
openssl s_client -host rubygems-china.oss-cn-hangzhou.aliyuncs.com -port 443
```
