### ISSUE TITLE
win7下安装sass失败，提示ruby证书不对？

### ISSUE THREAD

**Issue by fh-combo** [alibaba/ruby.taobao.org#52]
执行
gem sources --add https://ruby.taobao.org/ --remove https://rubygems.org/
提示：
Error fetching https://ruby.taobao.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: ce
rtificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/spe
cs.4.8.gz)

我用的是win系统，这个命令有影响吗？正确的该怎么做

**Comment by crhan** [comment]
跟 #54 情况类似，麻烦给一下 `openssl s_client -host rubygems-china.oss-cn-hangzhou.aliyuncs.com -port 443` 的输出

**Comment by crhan** [comment]
统一去 #54 更新最新情况，这边关闭了
