### ISSUE TITLE
Error fetching https://ruby.taobao.org/

### ISSUE THREAD

**Issue by weihong1028** [alibaba/ruby.taobao.org#53]
![image](https://cloud.githubusercontent.com/assets/7336582/14096278/e34ae3ea-f599-11e5-91c4-d63b26746289.png)

**Comment by crhan** [comment]
跟 #54 情况类似，麻烦给一下 `openssl s_client -host rubygems-china.oss-cn-hangzhou.aliyuncs.com -port 443` 的输出

**Comment by weihong1028** [comment]
我使用了 http://gems.ruby-china.org/ 做为源解决了这个问题

**Comment by crhan** [comment]
well Done, and issue closed

**Comment by frehaiku** [comment]
λ openssl s_client -host rubygems-china.oss-cn-hangzhou.aliyuncs.com -port 443
CONNECTED(00000003)
depth=2 C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign Organization Validation CA - SHA256 - G2
verify return:1
depth=0 C = CN, ST = ZheJiang, L = HangZhou, O = "Alibaba (China) Technology Co., Ltd.", CN = *.oss-cn-hangzhou.aliyuncs.com

## verify return:1

Certificate chain
 0 s:/C=CN/ST=ZheJiang/L=HangZhou/O=Alibaba (China) Technology Co., Ltd./CN=*.oss-cn-hangzhou.aliyuncs.com
   i:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - SHA256 - G2
 1 s:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - SHA256 - G2
   i:/C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
 2 s:/C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA

##    i:/C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA

Server certificate
-----BEGIN CERTIFICATE-----
MIIFgDCCBGigAwIBAgISESGHtzSBVPVLoh2W9/cBpWFAMA0GCSqGSIb3DQEBCwUA
MGYxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMTwwOgYD
VQQDEzNHbG9iYWxTaWduIE9yZ2FuaXphdGlvbiBWYWxpZGF0aW9uIENBIC0gU0hB
MjU2IC0gRzIwHhcNMTYwMjE5MDkwNzU2WhcNMTcwMjE5MDkwNzU2WjCBizELMAkG
A1UEBhMCQ04xETAPBgNVBAgTCFpoZUppYW5nMREwDwYDVQQHEwhIYW5nWmhvdTEt
MCsGA1UEChMkQWxpYmFiYSAoQ2hpbmEpIFRlY2hub2xvZ3kgQ28uLCBMdGQuMScw
JQYDVQQDDB4qLm9zcy1jbi1oYW5nemhvdS5hbGl5dW5jcy5jb20wggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQClVLZrrOMcNDJpLKIBISzw2R+f5UJSEpdv
xSZS7oH2NkRdib/CUwU+b6wBe1jx5UKh9PlyWj+mZggq7/jdPHcmAQvNtgUKd7LF
uU1WY1q5I1JbxDGISwuXZa1ayGSEIQxQn9E329s2U62X/nAmHyu4pDsYDSnOujKq
XXEghvX5O7V8cH+YW0FHS2GGqWoUFnctSRP16z79jC/fL5AJ4gETYcO2R2kVX+4C
NWBBEcpe5F18ZoJEYJprymVUeI/Qc8p5jP+rxfBoOCo2l2BG0IewJmD/BXl4z1Xv
geWgD7jc4nbaV3q+zpZtXaX9eKGcGVvQlA+9p89eARlgvwZ6Gy+NAgMBAAGjggIA
MIIB/DAOBgNVHQ8BAf8EBAMCBaAwSQYDVR0gBEIwQDA+BgZngQwBAgIwNDAyBggr
BgEFBQcCARYmaHR0cHM6Ly93d3cuZ2xvYmFsc2lnbi5jb20vcmVwb3NpdG9yeS8w
RwYDVR0RBEAwPoIeKi5vc3MtY24taGFuZ3pob3UuYWxpeXVuY3MuY29tghxvc3Mt
Y24taGFuZ3pob3UuYWxpeXVuY3MuY29tMAkGA1UdEwQCMAAwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMEkGA1UdHwRCMEAwPqA8oDqGOGh0dHA6Ly9jcmwu
Z2xvYmFsc2lnbi5jb20vZ3MvZ3Nvcmdhbml6YXRpb252YWxzaGEyZzIuY3JsMIGg
BggrBgEFBQcBAQSBkzCBkDBNBggrBgEFBQcwAoZBaHR0cDovL3NlY3VyZS5nbG9i
YWxzaWduLmNvbS9jYWNlcnQvZ3Nvcmdhbml6YXRpb252YWxzaGEyZzJyMS5jcnQw
PwYIKwYBBQUHMAGGM2h0dHA6Ly9vY3NwMi5nbG9iYWxzaWduLmNvbS9nc29yZ2Fu
aXphdGlvbnZhbHNoYTJnMjAdBgNVHQ4EFgQU1IDK1BdAMkP8AzeI+UxCOYYbYqYw
HwYDVR0jBBgwFoAUlt5h8b0cFilTHMDMfTuDAEDmGnwwDQYJKoZIhvcNAQELBQAD
ggEBAJlhaikpc+p1we3gKJKN1VQrtGW1yFjHfx8xSAn9Ypk/LFIgmTWoA60/f5mJ
XSGJ5p0znBTx0dlcWFfu/7fWbxGzVeYVzF/KliJVYhagL7D+DsZfYkSdeC3wiXuA
0PQkY9vkm46L6c/HYucRiFXpqLosKG1SDWNYNt1H7vkwMCvOFEoPe5kuTihHLH+9
odZhJDO5cLDD3wKCJX4tYD/uF13RbUkAK7gcy1DTVKNIkP07BmMiL8ceEvTnbyPj
c4baSGNFaHALNY3VbQBN8oVyz/a8Uf/tbVdKTlP/4UR589toMJZsVnrhma3ha3im
cQjV13vhXvw2AbpjL/cLg9LGW6Q=
-----END CERTIFICATE-----
subject=/C=CN/ST=ZheJiang/L=HangZhou/O=Alibaba (China) Technology Co., Ltd./CN=*.oss-cn-hangzhou.aliyuncs.com

## issuer=/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - SHA256 - G2

No client certificate CA names sent
Peer signing digest: SHA512

## Server Temp Key: ECDH, P-256, 256 bits

## SSL handshake has read 4115 bytes and written 442 bytes

New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 889D1F3DE9450741D645FA5741CF6FF8BE6313C59FDE61A6ECCE1ABDA37C4807
    Session-ID-ctx:
    Master-Key: 608E0390262FE24AF95145D42152FB5E0D327332930235FC142FD2198DA2064DEC332CF107B0EA9069C6941250A17CAC
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 06 2a ac 26 d1 c3 01 b5-c8 7b 56 9f 81 4b a3 4d   .*.&.....{V..K.M
    0010 - fa de 0e a9 27 6f ca 24-9c ca 4e 49 2b a0 ac db   ....'o.$..NI+...
    0020 - 56 23 84 00 fc 07 ae 51-71 18 1c 1a 38 3a 86 ec   V#.....Qq...8:..
    0030 - 7f 5c 51 b9 61 04 68 84-e4 ec d8 1a 84 d9 37 bc   .\Q.a.h.......7.
    0040 - 3b 0c 95 8f bd ba 7b 8a-02 d7 61 de ce eb e9 47   ;.....{...a....G
    0050 - d9 d8 4e 11 41 16 2e d6-4e 04 28 5b 1f fc 7d 37   ..N.A...N.([..}7
    0060 - 2f d6 fb fd eb 04 3c 13-dd 5c d9 80 55 6e 5f 6a   /.....<....Un_j
    0070 - 93 4f 71 7a 76 e4 e8 26-db d0 10 32 79 ec 6b f3   .Oqzv..&...2y.k.
    0080 - 1b d7 4d 85 5a 4b 0a ff-0d ba 7b ed b2 1f 58 e5   ..M.ZK....{...X.
    0090 - f1 96 8a 73 0f 95 18 89-d6 7d 19 07 13 b6 22 81   ...s.....}....".
    00a0 - 1d 20 24 92 ac 26 4a ce-d2 07 28 42 bd 83 86 f1   . $..&J...(B....

```
Start Time: 1463546852
Timeout   : 300 (sec)
Verify return code: 0 (ok)
```

结果是这样的，还是提示下面的错误
Error fetching https://ruby.taobao.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

**Comment by weihong1028** [comment]
你将gem源换成 http://gems.ruby-china.org/ 试一下，我就是这样解决的

**Comment by weihong1028** [comment]
#66 这里已经说明了更换源

**Comment by frehaiku** [comment]
@weihong1028 原来是更换了源。咦，前辈你是BAT的吧？能帮我内推下吗

**Comment by weihong1028** [comment]
我不是BAT的员工，你搞错啦

**Comment by frehaiku** [comment]
搞错了，原来是你发表的issues

**Comment by yuangaofei** [comment]
把源更换成http://gems.ruby-china.org  即可    注意协议 是http 。

**Comment by yuangaofei** [comment]
把源更换成http://gems.ruby-china.org  即可    注意协议 是http 。

**Comment by yuangaofei** [comment]
把源更换成http://gems.ruby-china.org  即可    注意协议 是http 。

**Comment by yuangaofei** [comment]
把源更换成http://gems.ruby-china.org  即可    注意协议 是http 。

**Comment by yuangaofei** [comment]
把源更换成http://gems.ruby-china.org  即可    注意协议 是http 。

**Comment by czcys** [comment]
我也是这个问题  我换成http://gems.ruby-china.org之后就卡那儿了  这是什么情况
