### ISSUE TITLE
添加ruby源的时候出现error fetching错误

### ISSUE THREAD

**Issue by wlh-xm** [alibaba/ruby.taobao.org#55]
Error fetching https://ruby.taobao.org:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

咋回事。。。

**Comment by wlh-xm** [comment]
额，该问题在下面的几个issues中已经提到过了，采用http://blog.fens.me/jekyll-bootstarp-github/  中提到的下载证书文件，添加SSL_CERT_FILE环境变量，再gem sources -a https://ruby.taobao.org  就可以正常添加源了。。

**Comment by crhan** [comment]
统一去 #54 更新最新情况，这边关闭了.

从你的解决方案上面看，似乎是你电脑的 CA 证书不完整导致
