### ISSUE TITLE
gem install fpm fail( Failed to build gem native extension)

### ISSUE THREAD

**Issue by szhansen** [alibaba/ruby.taobao.org#56]
root@debian:~# gem install fpm
Building native extensions.  This could take a while...
ERROR:  Error installing fpm:
        ERROR: Failed to build gem native extension.

```
current directory: /var/lib/gems/2.1.0/gems/ffi-1.9.10/ext/ffi_c
```

/usr/bin/ruby2.1 -r ./siteconf20160403-23068-140ukd0.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86-linux/2.1.0/ffi-1.9.10/gem_make.out

root@debian:~# ruby -v
ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]
root@debian:~# gem list

**\* LOCAL GEMS ***

activesupport (4.2.6)
arr-pm (0.0.10)
backports (3.6.8)
bigdecimal (default: 1.2.4)
cabin (0.8.1)
clamp (0.6.5)
i18n (0.7.0)
io-console (default: 0.4.2)
json (default: 1.8.1)
mini_portile2 (2.0.0)
minitest (5.8.4, default: 4.7.5)
psych (default: 2.0.5)
rack (1.6.4)
rack-test (0.6.3)
rake (default: 10.1.0)
rdoc (default: 4.1.0)
test-unit (default: 2.1.5.0)
thread_safe (0.3.5)
tzinfo (1.2.2)
root@debian:~#

**Comment by szhansen** [comment]
root@debian:~# gem sources -l
**\* CURRENT SOURCES ***

https://ruby.taobao.org/
root@debian:~#

**Comment by crhan** [comment]
看起来跟我们的镜像没有什么关系，如果还是怀疑镜像有问题的话可以尝试切换回 https://rubygems.org/ 试试看是否问题消失了。
