### ISSUE TITLE
执行gem sources --add https://ruby.taobao.org 报错

### ISSUE THREAD

**Issue by linjingming** [alibaba/ruby.taobao.org#57]
执行gem sources --add https://ruby.taobao.org 报错提升如下
Error fetching https://ruby.taobao.org:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

请问 怎么解决

**Comment by hasbug** [comment]
哥们，貌似他们放弃了，看这里：http://www.oschina.net/news/71749/taobao-gems-ruby-china
不过试了，一样不行。
哥们，用这个，我刚添加上了
http://gems.github.com
命令：
gem sources -a http://gems.github.com

**Comment by crhan** [comment]
hi，请参考下 #54 今天应该是把问题定位 ok 了，尝试升级 rubygems 到 2.6.3 版本试试看

```
gem update --system
```

后续还有问题就到 #54 一起讨论，这边先关闭了
