### ISSUE TITLE
gem sources -a https://ruby.taobao.org/失败

### ISSUE THREAD

**Issue by qhLiu** [alibaba/ruby.taobao.org#59]
```
    Errno::ETIMEDOUT: Failed to open TCP connection to rubygems-china.oss-cn
```

-hangzhou.aliyuncs.com:443 (A connection attempt failed because the connected pa
rty did not properly respond after a period of time, or established connection f
ailed because connected host has failed to respond. - connect(2) for "rubygems-c
hina.oss-cn-hangzhou.aliyuncs.com" port 443) (https://ruby.taobao.org/specs.4.8.
gz)

**Comment by crhan** [comment]
这个不常见，后来症状消失了吗？

**Comment by qhLiu** [comment]
并没有消失，当时这个问题困扰了我一天的时间，一直得不到解决，以至于我改用了ruby-china的镜像服务就可用了。

**Comment by crhan** [comment]
好，你先继续用那边的吧

我在外面旅游，暂时没办法帮您处理。抱歉给您带来不便。
