### ISSUE TITLE
为什么更新了淘宝的源，可是显示的还是ruby的源

### ISSUE THREAD

**Issue by sunjiali** [alibaba/ruby.taobao.org#60]
sunjiali@sunjiali-pc:~$ gem source -l
**\* CURRENT SOURCES ***

https://ruby.taobao.org/

sunjiali@sunjiali-pc:~$ sudo gem install bundler -V
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=bundler
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/quick/Marshal.4.8/bundler-1.11.2.gemspec.rz
302 Moved Temporarily
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/bundler-1.11.2.gemspec.rz)
sunjiali@sunjiali-pc:~$ 

求解。

**Comment by crhan** [comment]
试试看 sudo gem source -l

应该能发现玄机

sunjiali notifications@github.com于2016年4月17日 周日23:14写道：
