### ISSUE TITLE
gem sources --add https://ruby.taobao.org --remove https://rubygem.org出错

### ISSUE THREAD

**Issue by jxmyh99** [alibaba/ruby.taobao.org#61]
出错信息如下：
error fetching https://ruby.taobao.org/:SSL_connect returned = 1 error=0 state=SSLv3 read server certificate B: certficate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)
平台win8.1
ruby版本2.3.0
gem版本2.5.1

**Comment by crhan** [comment]
嗨，请看一下 #54 有跟进这个问题喔。。完全修复还要一点时间。

另外你试试看不带 https 的是否可以

zero notifications@github.com于2016年4月19日 周二11:21写道：
