### ISSUE TITLE
不用问证书问题了，更新已经废弃了，ruby-china上说的，维护的人走了，转gem source -a https://gems.ruby-china.org吧

### ISSUE THREAD

**Issue by forging2012** [alibaba/ruby.taobao.org#66]
gem source -a https://gems.ruby-china.org

**Comment by forging2012** [comment]
如何使用？

请尽可能用比较新的 RubyGems 版本，建议 2.6.x 以上。

$ gem update --system # 这里请翻墙一下
$ gem -v
2.6.3
$ gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/
$ gem sources -l
https://gems.ruby-china.org

# 确保只有 gems.ruby-china.org

如果你使用 Gemfile 和 Bundle (例如：Rails 项目)

你可以用 Bundler 的 Gem 源代码镜像命令。

$ bundle config mirror.https://rubygems.org https://gems.ruby-china.org
这样你不用改你的 Gemfile 的 source。

source 'https://rubygems.org/'
gem 'rails', '4.2.5'
...

**Comment by cnhappier** [comment]
证书一样有问题？

Error fetching https://gems.ruby-china.org:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: ce
rtificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)

**Comment by lzhr** [comment]
http://mirrors.aliyun.com/help/rubygems

**Comment by lzhr** [comment]
@cnhappier   http://mirrors.aliyun.com/rubygems/

**Comment by wahyd4** [comment]
@lzhr  👍 mirrors.aliyun.com 的速度也很快，希望不会一段时间后又不能使用了。

**Comment by qx** [comment]
ruby-china那个镜像不稳定,大部分时候也不快

**Comment by jony4** [comment]
证书一样有问题？

$ gem source -a https://gems.ruby-china.org --remove https://rubygems.org/ -V
Getting SRV record failed: DNS result has no information for _rubygems._tcp.gems.ruby-china.org
Error fetching https://gems.ruby-china.org:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://gems.ruby-china.org/specs.4.8.gz)
