### ISSUE TITLE
gem install cocoa pods失败

### ISSUE THREAD

**Issue by Aozorany** [alibaba/ruby.taobao.org#67]
ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from http://ruby.taobao.org/ - bad response Not Found 404 (http://ruby.taobao.org/latest_specs.4.8.gz)

**Comment by lzhr** [comment]
换成阿里云的试试  http://mirrors.aliyun.com/help/rubygems
