### ISSUE TITLE
gem之前是大写，改名为小写后同步不过来了

### ISSUE THREAD

**Issue by wvv8oo** [alibaba/ruby.taobao.org#69]
GEM: m2m，原来的名称是M2M，后来改成m2m，发现同步不过来了。

在rubygems.org上已经发布到0.2.0了，在taobao上还是0.1.3

https://rubygems.org/gems/m2m

```
gem search m2m

*** REMOTE GEMS ***

iterm2mintty (0.0.4)
M2M (0.1.3)
m2m_fast_insert (0.2.0)
osm2mongo (0.0.1)
spsclient_m2m (0.2.1)
```

**Comment by lzhr** [comment]
好像是淘宝镜像出问题了，换到阿里云试试？
rubygems   http://mirrors.aliyun.com/help/rubygems

**Comment by wvv8oo** [comment]
看样子还真是，之前貌似还没有问题，阿里云的同步确实没有问题
