### ISSUE TITLE
执行命令：gem sources --add https://ruby.taobao.org/ --remove https://rubygems.org/ 报错

### ISSUE THREAD

**Issue by ihlfo** [alibaba/ruby.taobao.org#72]
执行命令：gem sources --add https://ruby.taobao.org/ --remove https://rubygems.org/
报错，错误信息如下：
Error fetching https://ruby.taobao.org/:
        SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems-china.oss-cn-hangzhou.aliyuncs.com/specs.4.8.gz)

**Comment by amluck** [comment]
遇到同样的问题

**Comment by hexiyou** [comment]
对，同遇到

**Comment by jony4** [comment]
没人回复这个问题么？

**Comment by wendellsheh** [comment]
一样
