### ISSUE TITLE
cocoapods 版本较低

### ISSUE THREAD

**Issue by tangzhentao** [alibaba/ruby.taobao.org#76]
这里(https://rubygems.org/gems/cocoapods)在10月11号已经发布1.1.0.rc.3 了。而我们通过https://ruby.taobao.org/现在只能获取到cocoapods1.1.0.beta.2。

**Comment by maojj** [comment]
+1
不是15分钟一次吗？ 为啥没有更新

**Comment by ChengLuffy** [comment]
停止更新了 https://github.com/alibaba/ruby.taobao.org/issues/74
换 [ruby-china](https://gems.ruby-china.org) 解决。

**Comment by crhan** [comment]
302 到 ruby-china 了
