### ISSUE TITLE
失败,网络重定向...http,https均不行..

### ISSUE THREAD

**Issue by lubocheng** [alibaba/ruby.taobao.org#9]
~ # gem sources -a https://ruby.taobao.org
ERROR:  While executing gem ... (Errno::ENETRESET)
    Network dropped connection on reset - recvfrom(2)
~ # gem sources -a https://ruby.taobao.org
ERROR:  While executing gem ... (Errno::ENETRESET)
    Network dropped connection on reset - recvfrom(2)
就是这种错误..是我倒霉遇到吗??还是一直这样?

**Comment by qhwa** [comment]
可能是前几天的网络状况有问题，请再试一下
